name: master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release
    - name: Publish
      run: dotnet publish -c Release
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: CICDDemo
        path: /home/runner/work/CI_CD_Training/CI_CD_Training/CICDTraining/bin/Release/netcoreapp3.1/publish/
